# Site Settings
title: Media Channels & Platforms
email: miiro.paananen@windowslive.com
description: >
  My blog for Media Channels & Platforms
baseurl: "/site"
url: "http://cvltdesign.github.io"
twitter_username: miipsx
github_username:  cvltdesign
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
